### ISSUE TITLE
Znalezienie bibliotek

### ISSUE THREAD

**Issue by bartekb4** [BartlomiejWojcik/Gra-Snake-#1]

**Comment by bartekb4** [comment]
Proponuję użyć biblioteki Allegro, wydaje się najlepiej łączyć funkcjonalność z łatwością użycia. Jednocześnie pozostaję otwarty na inne propozycje.

**Comment by wojtekgrzela** [comment]
Proponowałbym jednak pozostać przy grze uruchamianej w konsoli, ze względu na mocno ograniczony czas projektu i ewentualną konieczność nauki nowych funkcjonalności związanych z biblioteką Allegro.

**Comment by BartlomiejWojcik** [comment]
Popieram Wojtka, jestem za tym aby pozostać przy konsoli.

**Comment by bartekb4** [comment]
Ok, nie mam nic przeciwko

**Comment by 1212ww** [comment]
tak

**Comment by BartlomiejWojcik** [comment]
No więc dobrze, piszemy w konsoli.
