### ISSUE TITLE
Funkcja Main do 24.05

### ISSUE THREAD

**Issue by wojtekgrzela** [BartlomiejWojcik/Gra-Snake-#14]
Złożenie w całość utworzonych klas.

**Comment by BartlomiejWojcik** [comment]
Funkcja main w dużym skrócie:
-pojawienie się manu gry  (case)
-gdy nowa gra:
-wprowadzenie przez użytkownika rozmiarów mapy
-utworzenie obiektu mapa
-wyrysowanie go 
-snake tworzy węża startowego rysuje go
-jedzenie tworzy obiekt (sprawdza czy nie jest na wężu jeśli tak tworzy nowy)
-food rysuje jedzenie na mapce
-zostaje sprawdzone czy gracz nacisną jakiś przycisk kierunku
-sprawdzenie czy wąż najedzie na jedzenie w danym kierunku ( jeśli tak zmiana długości węża, dodanie punktów)
- sprawdzenie czy najechał na siebie albo kaniec mapy (wtedy koniec gry)
- uśpienie na moment gry (szybkość węża)
-odświeżenie konsoli
- narysowanie mapy
-narysowanie węża w nowej pozycji
-jeśli zjadł jedzenie to usunięcie starego utworzenie nowego
- i wszystko się powtarza

**Comment by 1212ww** [comment]
proponuje plik snake.cpp powoli zacząć przekształcać w maina oraz dobrym pomysłem dla przejrzystości programu może być umieszczenie nagłówków funkcji oraz ich deklaracji w osobnych plikach
