### ISSUE TITLE
Przedstawienie pomysłów na klasy i funkcje

### ISSUE THREAD

**Issue by bartekb4** [BartlomiejWojcik/Gra-Snake-#2]

**Comment by BartlomiejWojcik** [comment]
A więc potrzebna będzie klasa Snake
Jej składowe to m.in. długość, położenie głowy, prędkość poruszania się
Metody początkowe położenie, zmiana prędkości, zmiana kierunku ruchu itd

**Comment by BartlomiejWojcik** [comment]
Klasa food? dotycząca pojawiających się obiektów które wąż a zjeść?

**Comment by wojtekgrzela** [comment]
Proponuję jedną klasę food, w której będziemy określać wydłużenie węża i/lub inne efekty po zjedzeniu.

**Comment by 1212ww** [comment]
klasa food to dobry pomysł bo podczas działania program będzie musiał wiele razy tworzyć obiekt klasy food która będzie zawierała koordynaty pojawiania się jedzenia oraz upewniała się, że jedzenie nie pojawi się w miejscu, w którym w trakcie zjadania poprzedniej kropki był wąż

**Comment by BartlomiejWojcik** [comment]
Tak i określała jakiego rodzaju pojawi się jedzenie, w sensie będzie jakiś procent szans że pojawi się jedzenie z dodatkowym bonusem

**Comment by 1212ww** [comment]
jakim bonusem?

**Comment by BartlomiejWojcik** [comment]
No np. bardziej go wydłużała albo czasowo zwiększała jego prędkość

**Comment by BartlomiejWojcik** [comment]
Albo na przykład utrudniała tak że przez pewien czas zmienia działanie kierunków klawiszy (naciskasz w lewo snake skręca w prawo)

**Comment by BartlomiejWojcik** [comment]
Ale to można zaimplementować w późniejszym czasie

**Comment by 1212ww** [comment]
pozostaje wybrać system

**Comment by BartlomiejWojcik** [comment]
Win?

**Comment by 1212ww** [comment]
chyba że ktoś preferuje linuxa lub coś innego

**Comment by bartekb4** [comment]
ja jestem za windowsem

**Comment by BartlomiejWojcik** [comment]
Ja też

**Comment by BartlomiejWojcik** [comment]
Macie jeszcze jakieś propozycje na klasy?

**Comment by wojtekgrzela** [comment]
Coś w stylu klasa mapa, bo gdzieś ten snake musi się poruszać, trzeba ustalić granice tego obszaru.

**Comment by bartekb4** [comment]
najlepiej tak, żeby użytkownik mógł podać wielkość mapy

**Comment by BartlomiejWojcik** [comment]
A i jeszcze metoda wykrywająca kolizję, czyli sprawdzająca czy głowa nie ma takich samych współrzędnych jak któryś inny punkt węża

**Comment by 1212ww** [comment]
wszystkie współrzędne i tak bedą musiały być określone
