### ISSUE TITLE
 Omówienie funkcjonalności i przedstawienie pomysłów

### ISSUE THREAD

**Issue by bartekb4** [BartlomiejWojcik/Gra-Snake-#3]

**Comment by bartekb4** [comment]
do 12.05

**Comment by BartlomiejWojcik** [comment]
A więc moje przemyślenia są następujące:
U podstaw gra będzie typową grą w węża. Po ograniczonym polu będzie poruszał się gracz i jego celem będzie zdobycie jak najwięcej punktów poprzez "zjadanie" pojawiającego się na planszy "jedzenia" które będzie jednocześnie wydłużało węża.
Gra uruchomiona w konsoli która kończy się gdy gracz wejdzie na ograniczenie mapy lub najedzie na ogon.
Uważam, że gracz powinien sam, przed rozpoczęciem wybierać rozmiar planszy i szybkość poruszania się węża.
To tyle na temat podstaw, dodatkowo po utworzeniu działającego prototypu dodatkowe funkcje które moglibyśmy dodać aby uatrakcyjnić grę to:
- różnego rodzaju jedzenie mające odmienne czasowe efekty
- zwiększenie poziomu trudności poprzez dodanie ścian w planszy
Zgadzacie się? 
Utworzę w repozytorium plik txt z tymi założeniami i dodawajcie tam swoje pomysły.
